# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/mrossign/QuOCS/QuOCS-pyqtinterface/quocs_pyqtinterface/gui/uifiles/ControlsTab.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1309, 795)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.controls_tab = QtWidgets.QTabWidget(Form)
        self.controls_tab.setObjectName("controls_tab")
        self.verticalLayout.addWidget(self.controls_tab)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.add_pulse_button = QtWidgets.QPushButton(Form)
        self.add_pulse_button.setObjectName("add_pulse_button")
        self.horizontalLayout.addWidget(self.add_pulse_button)
        self.add_parameter_button = QtWidgets.QPushButton(Form)
        self.add_parameter_button.setObjectName("add_parameter_button")
        self.horizontalLayout.addWidget(self.add_parameter_button)
        self.add_time_button = QtWidgets.QPushButton(Form)
        self.add_time_button.setObjectName("add_time_button")
        self.horizontalLayout.addWidget(self.add_time_button)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.remove_control_button = QtWidgets.QPushButton(Form)
        self.remove_control_button.setObjectName("remove_control_button")
        self.horizontalLayout.addWidget(self.remove_control_button)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.add_pulse_button.setText(_translate("Form", "Add Pulse"))
        self.add_parameter_button.setText(_translate("Form", "Add Parameter"))
        self.add_time_button.setText(_translate("Form", "Add Time"))
        self.remove_control_button.setText(_translate("Form", "Remove control"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
